"""Demo: tool-driven market analysis with evidence receipts.

Run:  python examples/market_analysis.py

Requires Claude credentials — either ``ANTHROPIC_API_KEY`` or an ``ant auth
login`` profile.

What to watch for in the output: the ``EVIDENCE`` block is not written by the
model. The analyst proposes its own evidence list and the framework discards it,
substituting one line per tool call the dispatcher actually executed. Compare
any figure in the brief against those receipts.
"""

from __future__ import annotations

import sys

from finagent_nexus.agents import MarketAnalyst
from finagent_nexus.config import Settings
from finagent_nexus.llm import AgentError, ClaudeClient
from finagent_nexus.state import ClientRequest, Mandate, Plan, PlanStep
from finagent_nexus.tools import SyntheticMarketData, ToolDispatcher

REQUEST = ClientRequest(
    client_id="CL-DEMO-0142",
    objective="Balanced growth within a Shari'ah-compliant mandate.",
    capital_usd=2_500_000,
    horizon_years=10,
    risk_tolerance="balanced",
    jurisdiction="SA",
    mandate=Mandate.SHARIA,
    constraints=["No leveraged products.", "Minimum 25% in income-generating assets."],
)

PLAN = Plan(
    thesis=(
        "Anchor the book in sukuk for income stability, then add Shari'ah-screened "
        "equity and a real-asset hedge sized to a balanced tolerance."
    ),
    universe=["SUKUK.GCC", "2222.SR", "1120.SR", "SPUS", "GLD"],
    steps=[
        PlanStep(
            id="S1",
            agent="MarketAnalyst",
            objective="Establish risk metrics for every proposed holding.",
            success_criteria="Annualised volatility, max drawdown and 95% VaR recorded per symbol.",
        ),
        PlanStep(
            id="S2",
            agent="MarketAnalyst",
            objective="Confirm each holding's AAOIFI screening ratios.",
            success_criteria="Debt, interest-bearing securities and impure revenue ratios recorded.",
        ),
    ],
)


def _use_utf8_stdout() -> None:
    """Windows consoles default to cp1252, which cannot encode the report glyphs.

    Without this, printing a threshold such as "<=" rendered as U+2264 raises
    UnicodeEncodeError and the run dies after the work is already done. Reported
    output is a deliverable, not a debug aid; it should not depend on the host
    console's code page.
    """
    for stream in (sys.stdout, sys.stderr):
        reconfigure = getattr(stream, "reconfigure", None)
        if reconfigure is not None:
            reconfigure(encoding="utf-8", errors="replace")


def main() -> int:
    _use_utf8_stdout()
    settings = Settings.from_env()
    analyst = MarketAnalyst(
        ClaudeClient(settings), ToolDispatcher(SyntheticMarketData())
    )

    print("=" * 78)
    print("FinAgent-Nexus — MarketAnalyst")
    print("=" * 78)
    print(f"Model: {settings.analyst_model} at effort '{settings.effort}'")
    print(f"Universe: {', '.join(PLAN.universe)}\n")

    try:
        result = analyst.run(REQUEST, PLAN)
    except AgentError as exc:
        print(f"The analyst could not complete the brief: {exc}", file=sys.stderr)
        return 1

    brief = result.value

    print(f"REGIME\n  {brief.regime}\n")

    print("KEY RISKS")
    for risk in brief.key_risks:
        print(f"  · {risk}")

    print(f"\n{'Symbol':<12}{'Exp. return':>12}{'Volatility':>12}{'Confidence':>12}")
    print("-" * 48)
    for view in brief.views:
        print(
            f"{view.symbol:<12}{view.expected_return_pct:>11.2f}%"
            f"{view.volatility_pct:>11.2f}%{view.confidence:>12.2f}"
        )

    print("\nTHESES")
    for view in brief.views:
        print(f"  {view.symbol}: {view.thesis}")

    print(f"\nEVIDENCE — {len(result.tool_calls)} tool calls actually executed")
    print("(generated by the dispatcher, not authored by the model)")
    for line in brief.evidence:
        print(f"  {line}")

    errors = [record for record in result.tool_calls if record.is_error]
    if errors:
        print(f"\n{len(errors)} tool call(s) returned errors — the analyst was told:")
        for record in errors:
            print(f"  {record.as_evidence()}")

    usage = result.usage
    print(
        f"\nCost: {usage.get('input_tokens', 0)} in / {usage.get('output_tokens', 0)} out"
        f" ({usage.get('cache_read_input_tokens', 0)} served from cache)"
        f" in {result.latency_ms} ms"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
